=== didacusAbella/MobileSolutions/src/main/webapp/WEB-INF/database/cliente.dtd
<!ELEMENT dati (cliente+)>
<!ELEMENT cliente (nome,cognome,cofiscale,tipoindirizzo,indirizzo,cap,citta,provincia,telcasa,telcell,fax,username,password,email,clausola1,clausola2)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT cognome (#PCDATA)>
<!ELEMENT cofiscale (#PCDATA)>
<!ELEMENT tipoindirizzo (#PCDATA)>
<!ELEMENT indirizzo (#PCDATA)>
<!ELEMENT cap (#PCDATA)>
<!ELEMENT citta (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT telcasa (#PCDATA)>
<!ELEMENT telcell (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT clausola1 (#PCDATA)>
<!ELEMENT clausola2 (#PCDATA)>

=== didacusAbella/MobileSolutions/src/main/webapp/WEB-INF/database/cliente.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE dati SYSTEM "cliente.dtd">
<dati>
 <cliente>
  <nome>umberto</nome>
  <cognome>attanasio</cognome>
  <cofiscale>nrfjtnhjnyjn</cofiscale>
  <tipoindirizzo>Largo</tipoindirizzo>
  <indirizzo>klnjfkljbngbk</indirizzo>
  <cap>5894759847</cap>
  <citta>efnrjkgtntkjbn</citta>
  <provincia>Agrigento</provincia>
  <telcasa>49875869</telcasa>
  <telcell>347854789</telcell>
  <fax>54757</fax>
  <username>umber</username>
  <password>umber</password>
  <email>thtyh@gg.oy</email>
  <clausola1>Si</clausola1>
  <clausola2>Si</clausola2>
 </cliente>
 <cliente>
  <nome>luigi</nome>
  <cognome>baggi</cognome>
  <cofiscale>ttjgjjfgjghghjfjf</cofiscale>
  <tipoindirizzo>Largo</tipoindirizzo>
  <indirizzo>casal</indirizzo>
  <cap>88</cap>
  <citta>sal</citta>
  <provincia>Agrigento</provincia>
  <telcasa>65677</telcasa>
  <telcell>56777</telcell>
  <fax>66555</fax>
  <username>luigi</username>
  <password>strong</password>
  <email>4tgtghth@ggg.it</email>
  <clausola1>Si</clausola1>
  <clausola2>Si</clausola2>
 </cliente>
 <cliente>
  <nome>fgthth</nome>
  <cognome>ththyh</cognome>
  <cofiscale>thyjyjyu</cofiscale>
  <tipoindirizzo>Largo</tipoindirizzo>
  <indirizzo>thyhjyju</indirizzo>
  <cap>676767</cap>
  <citta>fbghnhm</citta>
  <provincia>Agrigento</provincia>
  <telcasa>456546757</telcasa>
  <telcell>5657765</telcell>
  <fax>565757</fax>
  <username>5ththth</username>
  <password>fghtght</password>
  <email>rgthyt@hth</email>
  <clausola1>Si</clausola1>
  <clausola2 />
 </cliente>
 <cliente>
  <nome>yhyjy</nome>
  <cognome>thyjj</cognome>
  <cofiscale>tyhjyjuju</cofiscale>
  <tipoindirizzo>Largo</tipoindirizzo>
  <indirizzo>yhjyj</indirizzo>
  <cap>yhjyjyuj</cap>
  <citta>yhjyjyjy</citta>
  <provincia>Agrigento</provincia>
  <telcasa>yjyj</telcasa>
  <telcell>yjyj</telcell>
  <fax>yjyjuy</fax>
  <username>yjyjyuj</username>
  <password>yjyjy</password>
  <email>yhjyjuj</email>
  <clausola1>Si</clausola1>
  <clausola2 />
 </cliente>
 <cliente>
  <nome />
  <cognome />
  <cofiscale />
  <tipoindirizzo>Vicolo</tipoindirizzo>
  <indirizzo />
  <cap />
  <citta />
  <provincia>Agrigento</provincia>
  <telcasa />
  <telcell />
  <fax />
  <username />
  <password />
  <email />
  <clausola1 />
  <clausola2 />
 </cliente>
</dati>
