=== didacusAbella/MobileSolutions/src/main/webapp/WEB-INF/database/ordini.dtd
<!ELEMENT data (ordini+)>
<!ELEMENT ordini (idordine, datainoltro, modalitaSpe, modalitaPay, totalePag, cliente)>
<!ELEMENT idordine (#PCDATA)>
<!ELEMENT datainoltro (#PCDATA)>
<!ELEMENT modalitaSpe (#PCDATA)>
<!ELEMENT modalitaPay (#PCDATA)>
<!ELEMENT totalePag (#PCDATA)>
<!ELEMENT cliente (#PCDATA)>

=== didacusAbella/MobileSolutions/src/main/webapp/WEB-INF/database/ordini.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE data SYSTEM "ordini.dtd">
<data>
 <ordini>
  <idordine>1</idordine>
  <datainoltro>Mon Feb 25 19:41:32 CET 2008</datainoltro>
  <modalitaSpe>raccomandata</modalitaSpe>
  <modalitaPay>paypal</modalitaPay>
  <totalePag>310</totalePag>
  <cliente>umber</cliente>
 </ordini>
 <ordini>
  <idordine>2</idordine>
  <datainoltro>Mon Feb 25 19:42:44 CET 2008</datainoltro>
  <modalitaSpe>raccomandata</modalitaSpe>
  <modalitaPay>postapay</modalitaPay>
  <totalePag>310</totalePag>
  <cliente>luigi</cliente>
 </ordini>
 <ordini>
  <idordine>3</idordine>
  <datainoltro>Mon Feb 25 19:51:03 CET 2008</datainoltro>
  <modalitaSpe />
  <modalitaPay />
  <totalePag />
  <cliente>umber</cliente>
 </ordini>
 <ordini>
  <idordine>4</idordine>
  <datainoltro>Mon Feb 25 19:59:07 CET 2008</datainoltro>
  <modalitaSpe>raccomandata</modalitaSpe>
  <modalitaPay>paypal</modalitaPay>
  <totalePag>460</totalePag>
  <cliente>luigi</cliente>
 </ordini>
</data>
