=== didacusAbella/MobileSolutions/src/main/webapp/WEB-INF/database/vendite.dtd
<!ELEMENT data (vendita+)>
<!ELEMENT vendita (marca, modello, prezzo, cliente)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modello (#PCDATA)>
<!ELEMENT prezzo (#PCDATA)>
<!ELEMENT cliente (#PCDATA)>

=== didacusAbella/MobileSolutions/src/main/webapp/WEB-INF/database/vendite.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE data SYSTEM "vendite.dtd">
<data>
 <vendita>
  <marca>nokia</marca>
  <modello>6630</modello>
  <prezzo>150</prezzo>
  <cliente>umber</cliente>
 </vendita>
 <vendita>
  <marca>nokia</marca>
  <modello>6630</modello>
  <prezzo>150</prezzo>
  <cliente>umber</cliente>
 </vendita>
 <vendita>
  <marca>nokia</marca>
  <modello>6630</modello>
  <prezzo>150</prezzo>
  <cliente>luigi</cliente>
 </vendita>
 <vendita>
  <marca>nokia</marca>
  <modello>6630</modello>
  <prezzo>150</prezzo>
  <cliente>luigi</cliente>
 </vendita>
 <vendita>
  <marca>nokia</marca>
  <modello>6630</modello>
  <prezzo>150</prezzo>
  <cliente>umber</cliente>
 </vendita>
 <vendita>
  <marca>nokia</marca>
  <modello>6630</modello>
  <prezzo>150</prezzo>
  <cliente>luigi</cliente>
 </vendita>
</data>
